Repository cbeleites/hyperSpec, pull requests merged in 2020-08, with the labels that each got.

#251 Update README.md
  .gitignore
  README.md
  project.Rproj
Labels: documentation :blue_book:

#258 Feature/review documentation (A to L)
  hyperSpec/R/Arith.R
  hyperSpec/R/Colors.R
  hyperSpec/R/Compare.R
  hyperSpec/R/DollarNames.R
  hyperSpec/R/aggregate.R
  hyperSpec/R/apply.R
  hyperSpec/R/as.data.frame.R
  hyperSpec/R/barbiturates.R
  hyperSpec/R/bind.R
  hyperSpec/R/chk.hy.R
  hyperSpec/R/colMeans.R
  hyperSpec/R/collapse.R
  hyperSpec/R/count_lines.R
  hyperSpec/R/cov.R
  hyperSpec/R/decomposition.R
  hyperSpec/R/deprecated.R
  hyperSpec/R/dim.R
  hyperSpec/R/dimnames.R
  hyperSpec/R/droplevels.R
  hyperSpec/R/empty.R
  hyperSpec/R/expand.R
  hyperSpec/R/extract.R
  hyperSpec/R/fileio.optional.R
  hyperSpec/R/fix_spc_colnames.R
  hyperSpec/R/flu.R
  hyperSpec/R/guesswavelength.R
  hyperSpec/R/hyperspec-class.R
  hyperSpec/R/hyperspec-package.R
  hyperSpec/R/initialize.R
  hyperSpec/R/labels.R
  hyperSpec/R/laser.R
  hyperSpec/R/matlab.palette.R
Labels: documentation :blue_book:

#256 Feature/deprecate ggplot2
  codecov.yml
  hyperSpec/DESCRIPTION
  hyperSpec/NEWS.md
  hyperSpec/R/DEPRECATED-ggplot2.R
  hyperSpec/R/deprecation-messages.R
  hyperSpec/R/options.R
  hyperSpec/R/qplot.R
  hyperSpec/R/qplotmixmap.R
  hyperSpec/_pkgdown.yml
Labels: enhancement

#264 Feature/263 deprecate functions moved to hySpc.read.txt
  hyperSpec/DESCRIPTION
  hyperSpec/NEWS.md
  hyperSpec/R/DEPRECATED-count_lines.R
  hyperSpec/R/DEPRECATED-read.asc.Andor.R
  hyperSpec/R/DEPRECATED-read.asc.PerkinElmer.R
  hyperSpec/R/DEPRECATED-read.txt.Horiba.R
  hyperSpec/R/DEPRECATED-read.txt.Renishaw.R
  hyperSpec/R/DEPRECATED-read.txt.Shimadzu.R
  hyperSpec/R/DEPRECATED-read.txt.Witec.R
  hyperSpec/R/DEPRECATED-read.txt.long.R
  hyperSpec/R/DEPRECATED-read.txt.wide.R
  hyperSpec/R/DEPRECATED-wc.R
  hyperSpec/R/deprecation-messages.R
  hyperSpec/R/read.ini.R
  hyperSpec/R/read.mat.Witec.R
  hyperSpec/R/write.txt.long.R
  hyperSpec/R/write.txt.wide.R
  hyperSpec/_pkgdown.yml
Labels: enhancement

#265 Change "I" to "We" to make it sound like a team project
  hyperSpec/vignettes/fileio.Rmd
Labels: vignette :green_book:

#269 Feature/vign edits
  hyperSpec/vignettes/fileio.Rmd
Labels: documentation :blue_book:, enhancement, vignette :green_book:

#273 Feature/Get list of available hySpc packages
  hyperSpec/DESCRIPTION
  hyperSpec/NEWS.md
  hyperSpec/R/hy_browse_homepage.R
  hyperSpec/R/hy_list_available_hySpc_packages.R
Labels: enhancement
