Repository cbeleites/hyperSpec, pull requests merged in 2020-06, with the labels that each got.

#94 Translate vignettes
  .gitignore
  hyperSpec/DESCRIPTION
  hyperSpec/vignettes/.gitignore
  hyperSpec/vignettes/baseline.Rmd
  hyperSpec/vignettes/chondro.Rmd
  hyperSpec/vignettes/fileio.Rmd
  hyperSpec/vignettes/flu.Rmd
  hyperSpec/vignettes/hyperspec.Rmd
  hyperSpec/vignettes/laser.Rmd
  hyperSpec/vignettes/man/080606d-flip-ausw.jpg
  hyperSpec/vignettes/man/elsevier-with-titles.csl
  hyperSpec/vignettes/man/intro--functions.RData
  hyperSpec/vignettes/man/intro--strukturhyperspec.png
  hyperSpec/vignettes/man/laser-rgl-3d.png
  hyperSpec/vignettes/man/plotting--fig-3D-01.png
  hyperSpec/vignettes/man/read.txt.PerkinElmer.R
  hyperSpec/vignettes/man/style.css
  hyperSpec/vignettes/man/vignette-default-settingsR.R
  hyperSpec/vignettes/man/vignette-functions.R
  hyperSpec/vignettes/man/vignette.css
  hyperSpec/vignettes/plotting.Rmd
Labels: documentation :blue_book:, vignettes :green_book:

#167 Fix/116 Update package startup message
  hyperSpec/R/zzz.R
Labels: documentation :blue_book:

#173 Vignette fileio is translated to Rmd
  hyperSpec/DESCRIPTION
  hyperSpec/vignettes/.gitignore
  hyperSpec/vignettes/.install_extras
  hyperSpec/vignettes/fileio--fileformats.txt
  hyperSpec/vignettes/fileio.Rmd
  hyperSpec/vignettes/read.ENVI.Nicolet.R
  hyperSpec/vignettes/read.txt.PerkinElmer.R
  hyperSpec/vignettes/style.css
  hyperSpec/vignettes/vignette-default-settings.R
Labels: vignette :green_book:

#159 Feature/131 Enable R-CMD-check on Git-Hub Actions
  .github/.gitignore
  .github/workflows/R-CMD-check.yaml
  .gitignore
  README.md
  hyperSpec/.Rbuildignore
  hyperSpec/.gitignore
  hyperSpec/R/chondro.R
  hyperSpec/data/barbiturates.rda
  hyperSpec/data/chondro.rda
  hyperSpec/data/flu.rda
  hyperSpec/data/laser.rda
  hyperSpec/data/paracetamol.rda
Labels: CI :cactus:, datasets :date:

#156 Feature/145 chondro replace
  hyperSpec/DESCRIPTION
  hyperSpec/R/aggregate.R
  hyperSpec/R/apply.R
  hyperSpec/R/as.data.frame.R
  hyperSpec/R/bind.R
  hyperSpec/R/chk.hy.R
  hyperSpec/R/collapse.R
  hyperSpec/R/cov.R
  hyperSpec/R/dim.R
  hyperSpec/R/dimnames.R
  hyperSpec/R/droplevels.R
  hyperSpec/R/empty.R
  hyperSpec/R/extract.R
  hyperSpec/R/hyperspec-package.R
  hyperSpec/R/labels.R
  hyperSpec/R/levelplot.R
  hyperSpec/R/map.sel.poly.R
  hyperSpec/R/mark.peak.R
  hyperSpec/R/matlab.palette.R
  hyperSpec/R/mean_sd.R
  hyperSpec/R/merge.R
  hyperSpec/R/mvtnorm.R
  hyperSpec/R/pearson.dist.R
  hyperSpec/R/plot.R
  hyperSpec/R/plotmap.R
  hyperSpec/R/plotspc.R
  hyperSpec/R/qplot.R
  hyperSpec/R/qplotmixmap.R
  hyperSpec/R/quantile.R
  hyperSpec/R/scale.R
  hyperSpec/R/show.R
  hyperSpec/R/spc.fit.poly.R
  hyperSpec/R/split.R
  hyperSpec/R/sweep.R
  hyperSpec/R/trellis.factor.key.R
  hyperSpec/R/wl.R
  hyperSpec/R/wl2i.R
Labels: documentation :blue_book:

#162 Feature/131 Enable code coverage checking with Codecov
  .github/workflows/R-CMD-check.yaml
  README.md
  hyperSpec/.Rbuildignore
  hyperSpec/DESCRIPTION
  hyperSpec/codecov.yml
Labels: CI :cactus:, unit test

#165 Fix/164 Update instructions in README
  README.md
Labels: documentation :blue_book:

#186 Add indicator that code in fileio.rmd is not evaluated
  hyperSpec/.gitignore
  hyperSpec/vignettes/fileio.Rmd
Labels: vignette :green_book:
