Repository cbeleites/hyperSpec, pull requests merged in 2021-02, with the labels that each got.

#219 Implement function to attach/load all hySpc.* packages
  hyperSpec/DESCRIPTION
  hyperSpec/NEWS.md
  hyperSpec/R/hy_attach.R
  hyperSpec/R/hy_list_installed_hySpc_packages.R
Labels: enhancement

#305 Update GHA workflows
  .github/workflows/R-CMD-check.yaml
  .github/workflows/pkgdown.yaml
Labels: CI :cactus:

#306 Update style and rename files
  .github/workflows/R-CMD-check.yaml
  hyperSpec/DESCRIPTION
  hyperSpec/R/Compare.R
  hyperSpec/R/DEPRECATED-scan.R
  hyperSpec/R/Summary.R
  hyperSpec/R/aggregate.R
  hyperSpec/R/as_hyperSpec.R
  hyperSpec/R/constants-regexps.R
  hyperSpec/R/constants-units.R
  hyperSpec/R/extract.R
  hyperSpec/R/extract_numbers.R
  hyperSpec/R/palette_colorblind.R
Labels: style :pencil2:

#310 Use title-case in headers of vignettes
  hyperSpec/vignettes/baseline.Rmd
  hyperSpec/vignettes/fileio.Rmd
  hyperSpec/vignettes/flu.Rmd
  hyperSpec/vignettes/hyperSpec.Rmd
  hyperSpec/vignettes/laser.Rmd
Labels: Topic: vignette :green_book:

#211 Feature/209 improve show()
  hyperSpec/NEWS.md
  hyperSpec/R/paste_row.R
  hyperSpec/R/show.R
Labels: Type: enhancement

#312 Use R 'release' instead of '4.0.3' on Linux again
  .github/workflows/R-CMD-check.yaml
Labels: Topic: CI :cactus:
